package tns.model.VO;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;

import tns.model.EO.EO_CustomersImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 20 18:52:24 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_CustomersRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CustomerId {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setCustomerId((DBSequence)value);
            }
        }
        ,
        CustomerNo {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getCustomerNo();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setCustomerNo((Number)value);
            }
        }
        ,
        CustomerType {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getCustomerType();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setCustomerType((String)value);
            }
        }
        ,
        CustomerName {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        AddressLine1 {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getAddressLine1();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setAddressLine1((String)value);
            }
        }
        ,
        AddressLine2 {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getAddressLine2();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setAddressLine2((String)value);
            }
        }
        ,
        City {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getCity();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setCity((String)value);
            }
        }
        ,
        Country {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getCountry();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        ZipCode {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getZipCode();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setZipCode((Number)value);
            }
        }
        ,
        PhoneNo {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getPhoneNo();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setPhoneNo((String)value);
            }
        }
        ,
        MobileNo {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getMobileNo();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setMobileNo((String)value);
            }
        }
        ,
        EmailAddress {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getEmailAddress();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setEmailAddress((String)value);
            }
        }
        ,
        ReceivablesAccount {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getReceivablesAccount();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setReceivablesAccount((Number)value);
            }
        }
        ,
        NtnNo {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getNtnNo();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setNtnNo((String)value);
            }
        }
        ,
        CnicNo {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getCnicNo();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setCnicNo((String)value);
            }
        }
        ,
        FederalTaxPayerId {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getFederalTaxPayerId();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setFederalTaxPayerId((Number)value);
            }
        }
        ,
        ProvincialTaxPayerId {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getProvincialTaxPayerId();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setProvincialTaxPayerId((Number)value);
            }
        }
        ,
        SalesPersonId {
            public Object get(VO_CustomersRowImpl obj) {
                return obj.getSalesPersonId();
            }

            public void put(VO_CustomersRowImpl obj, Object value) {
                obj.setSalesPersonId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(VO_CustomersRowImpl object);

        public abstract void put(VO_CustomersRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNO = AttributesEnum.CustomerNo.index();
    public static final int CUSTOMERTYPE = AttributesEnum.CustomerType.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int ADDRESSLINE1 = AttributesEnum.AddressLine1.index();
    public static final int ADDRESSLINE2 = AttributesEnum.AddressLine2.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int ZIPCODE = AttributesEnum.ZipCode.index();
    public static final int PHONENO = AttributesEnum.PhoneNo.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int RECEIVABLESACCOUNT = AttributesEnum.ReceivablesAccount.index();
    public static final int NTNNO = AttributesEnum.NtnNo.index();
    public static final int CNICNO = AttributesEnum.CnicNo.index();
    public static final int FEDERALTAXPAYERID = AttributesEnum.FederalTaxPayerId.index();
    public static final int PROVINCIALTAXPAYERID = AttributesEnum.ProvincialTaxPayerId.index();
    public static final int SALESPERSONID = AttributesEnum.SalesPersonId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_CustomersRowImpl() {
    }

    /**
     * Gets EO_Customers entity object.
     * @return the EO_Customers
     */
    public EO_CustomersImpl getEO_Customers() {
        return (EO_CustomersImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public DBSequence getCustomerId() {
        return (DBSequence)getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(DBSequence value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_NO using the alias name CustomerNo.
     * @return the CUSTOMER_NO
     */
    public DBSequence getCustomerNo() {
        return (DBSequence) getAttributeInternal(CUSTOMERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_NO using the alias name CustomerNo.
     * @param value value to set the CUSTOMER_NO
     */
    public void setCustomerNo(Number value) {
        setAttributeInternal(CUSTOMERNO, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_TYPE using the alias name CustomerType.
     * @return the CUSTOMER_TYPE
     */
    public String getCustomerType() {
        return (String) getAttributeInternal(CUSTOMERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_TYPE using the alias name CustomerType.
     * @param value value to set the CUSTOMER_TYPE
     */
    public void setCustomerType(String value) {
        setAttributeInternal(CUSTOMERTYPE, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_NAME using the alias name CustomerName.
     * @return the CUSTOMER_NAME
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_NAME using the alias name CustomerName.
     * @param value value to set the CUSTOMER_NAME
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for ADDRESS_LINE_1 using the alias name AddressLine1.
     * @return the ADDRESS_LINE_1
     */
    public String getAddressLine1() {
        return (String) getAttributeInternal(ADDRESSLINE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS_LINE_1 using the alias name AddressLine1.
     * @param value value to set the ADDRESS_LINE_1
     */
    public void setAddressLine1(String value) {
        setAttributeInternal(ADDRESSLINE1, value);
    }

    /**
     * Gets the attribute value for ADDRESS_LINE_2 using the alias name AddressLine2.
     * @return the ADDRESS_LINE_2
     */
    public String getAddressLine2() {
        return (String) getAttributeInternal(ADDRESSLINE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ADDRESS_LINE_2 using the alias name AddressLine2.
     * @param value value to set the ADDRESS_LINE_2
     */
    public void setAddressLine2(String value) {
        setAttributeInternal(ADDRESSLINE2, value);
    }

    /**
     * Gets the attribute value for CITY using the alias name City.
     * @return the CITY
     */
    public String getCity() {
        return (String) getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CITY using the alias name City.
     * @param value value to set the CITY
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for COUNTRY using the alias name Country.
     * @return the COUNTRY
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY using the alias name Country.
     * @param value value to set the COUNTRY
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for ZIP_CODE using the alias name ZipCode.
     * @return the ZIP_CODE
     */
    public Number getZipCode() {
        return (Number) getAttributeInternal(ZIPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ZIP_CODE using the alias name ZipCode.
     * @param value value to set the ZIP_CODE
     */
    public void setZipCode(Number value) {
        setAttributeInternal(ZIPCODE, value);
    }

    /**
     * Gets the attribute value for PHONE_NO using the alias name PhoneNo.
     * @return the PHONE_NO
     */
    public String getPhoneNo() {
        return (String) getAttributeInternal(PHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for PHONE_NO using the alias name PhoneNo.
     * @param value value to set the PHONE_NO
     */
    public void setPhoneNo(String value) {
        setAttributeInternal(PHONENO, value);
    }

    /**
     * Gets the attribute value for MOBILE_NO using the alias name MobileNo.
     * @return the MOBILE_NO
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILE_NO using the alias name MobileNo.
     * @param value value to set the MOBILE_NO
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @return the EMAIL_ADDRESS
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmailAddress.
     * @param value value to set the EMAIL_ADDRESS
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for RECEIVABLES_ACCOUNT using the alias name ReceivablesAccount.
     * @return the RECEIVABLES_ACCOUNT
     */
    public Number getReceivablesAccount() {
        return (Number) getAttributeInternal(RECEIVABLESACCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVABLES_ACCOUNT using the alias name ReceivablesAccount.
     * @param value value to set the RECEIVABLES_ACCOUNT
     */
    public void setReceivablesAccount(Number value) {
        setAttributeInternal(RECEIVABLESACCOUNT, value);
    }

    /**
     * Gets the attribute value for NTN_NO using the alias name NtnNo.
     * @return the NTN_NO
     */
    public String getNtnNo() {
        return (String) getAttributeInternal(NTNNO);
    }

    /**
     * Sets <code>value</code> as attribute value for NTN_NO using the alias name NtnNo.
     * @param value value to set the NTN_NO
     */
    public void setNtnNo(String value) {
        setAttributeInternal(NTNNO, value);
    }

    /**
     * Gets the attribute value for CNIC_NO using the alias name CnicNo.
     * @return the CNIC_NO
     */
    public String getCnicNo() {
        return (String) getAttributeInternal(CNICNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CNIC_NO using the alias name CnicNo.
     * @param value value to set the CNIC_NO
     */
    public void setCnicNo(String value) {
        setAttributeInternal(CNICNO, value);
    }

    /**
     * Gets the attribute value for FEDERAL_TAX_PAYER_ID using the alias name FederalTaxPayerId.
     * @return the FEDERAL_TAX_PAYER_ID
     */
    public Number getFederalTaxPayerId() {
        return (Number) getAttributeInternal(FEDERALTAXPAYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for FEDERAL_TAX_PAYER_ID using the alias name FederalTaxPayerId.
     * @param value value to set the FEDERAL_TAX_PAYER_ID
     */
    public void setFederalTaxPayerId(Number value) {
        setAttributeInternal(FEDERALTAXPAYERID, value);
    }

    /**
     * Gets the attribute value for PROVINCIAL_TAX_PAYER_ID using the alias name ProvincialTaxPayerId.
     * @return the PROVINCIAL_TAX_PAYER_ID
     */
    public Number getProvincialTaxPayerId() {
        return (Number) getAttributeInternal(PROVINCIALTAXPAYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROVINCIAL_TAX_PAYER_ID using the alias name ProvincialTaxPayerId.
     * @param value value to set the PROVINCIAL_TAX_PAYER_ID
     */
    public void setProvincialTaxPayerId(Number value) {
        setAttributeInternal(PROVINCIALTAXPAYERID, value);
    }

    /**
     * Gets the attribute value for SALES_PERSON_ID using the alias name SalesPersonId.
     * @return the SALES_PERSON_ID
     */
    public Number getSalesPersonId() {
        return (Number) getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALES_PERSON_ID using the alias name SalesPersonId.
     * @param value value to set the SALES_PERSON_ID
     */
    public void setSalesPersonId(Number value) {
        setAttributeInternal(SALESPERSONID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
