package tns.model.EO;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 19 22:10:15 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EO_CustomersImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CustomerId {
            public Object get(EO_CustomersImpl obj) {
                return obj.getCustomerId();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setCustomerId((DBSequence)value);
            }
        }
        ,
        CustomerNo {
            public Object get(EO_CustomersImpl obj) {
                return obj.getCustomerNo();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setCustomerNo((DBSequence)value);
            }
        }
        ,
        CustomerType {
            public Object get(EO_CustomersImpl obj) {
                return obj.getCustomerType();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setCustomerType((String)value);
            }
        }
        ,
        CustomerName {
            public Object get(EO_CustomersImpl obj) {
                return obj.getCustomerName();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        AddressLine1 {
            public Object get(EO_CustomersImpl obj) {
                return obj.getAddressLine1();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setAddressLine1((String)value);
            }
        }
        ,
        AddressLine2 {
            public Object get(EO_CustomersImpl obj) {
                return obj.getAddressLine2();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setAddressLine2((String)value);
            }
        }
        ,
        City {
            public Object get(EO_CustomersImpl obj) {
                return obj.getCity();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setCity((String)value);
            }
        }
        ,
        Country {
            public Object get(EO_CustomersImpl obj) {
                return obj.getCountry();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setCountry((String)value);
            }
        }
        ,
        ZipCode {
            public Object get(EO_CustomersImpl obj) {
                return obj.getZipCode();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setZipCode((Number)value);
            }
        }
        ,
        PhoneNo {
            public Object get(EO_CustomersImpl obj) {
                return obj.getPhoneNo();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setPhoneNo((String)value);
            }
        }
        ,
        MobileNo {
            public Object get(EO_CustomersImpl obj) {
                return obj.getMobileNo();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setMobileNo((String)value);
            }
        }
        ,
        EmailAddress {
            public Object get(EO_CustomersImpl obj) {
                return obj.getEmailAddress();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setEmailAddress((String)value);
            }
        }
        ,
        ReceivablesAccount {
            public Object get(EO_CustomersImpl obj) {
                return obj.getReceivablesAccount();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setReceivablesAccount((Number)value);
            }
        }
        ,
        NtnNo {
            public Object get(EO_CustomersImpl obj) {
                return obj.getNtnNo();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setNtnNo((String)value);
            }
        }
        ,
        CnicNo {
            public Object get(EO_CustomersImpl obj) {
                return obj.getCnicNo();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setCnicNo((String)value);
            }
        }
        ,
        FederalTaxPayerId {
            public Object get(EO_CustomersImpl obj) {
                return obj.getFederalTaxPayerId();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setFederalTaxPayerId((Number)value);
            }
        }
        ,
        ProvincialTaxPayerId {
            public Object get(EO_CustomersImpl obj) {
                return obj.getProvincialTaxPayerId();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setProvincialTaxPayerId((Number)value);
            }
        }
        ,
        SalesPersonId {
            public Object get(EO_CustomersImpl obj) {
                return obj.getSalesPersonId();
            }

            public void put(EO_CustomersImpl obj, Object value) {
                obj.setSalesPersonId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(EO_CustomersImpl object);

        public abstract void put(EO_CustomersImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERNO = AttributesEnum.CustomerNo.index();
    public static final int CUSTOMERTYPE = AttributesEnum.CustomerType.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int ADDRESSLINE1 = AttributesEnum.AddressLine1.index();
    public static final int ADDRESSLINE2 = AttributesEnum.AddressLine2.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int ZIPCODE = AttributesEnum.ZipCode.index();
    public static final int PHONENO = AttributesEnum.PhoneNo.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int RECEIVABLESACCOUNT = AttributesEnum.ReceivablesAccount.index();
    public static final int NTNNO = AttributesEnum.NtnNo.index();
    public static final int CNICNO = AttributesEnum.CnicNo.index();
    public static final int FEDERALTAXPAYERID = AttributesEnum.FederalTaxPayerId.index();
    public static final int PROVINCIALTAXPAYERID = AttributesEnum.ProvincialTaxPayerId.index();
    public static final int SALESPERSONID = AttributesEnum.SalesPersonId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EO_CustomersImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("tns.model.EO.EO_Customers");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for CustomerId, using the alias name CustomerId.
     * @return the CustomerId
     */
    public DBSequence getCustomerId() {
        return (DBSequence)getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerId.
     * @param value value to set the CustomerId
     */
    public void setCustomerId(DBSequence value) {
        setAttributeInternal(CUSTOMERID, value);
    }


    /**
     * Gets the attribute value for CustomerType, using the alias name CustomerType.
     * @return the CustomerType
     */
    public String getCustomerType() {
        return (String)getAttributeInternal(CUSTOMERTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerType.
     * @param value value to set the CustomerType
     */
    public void setCustomerType(String value) {
        setAttributeInternal(CUSTOMERTYPE, value);
    }

    /**
     * Gets the attribute value for CustomerName, using the alias name CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String)getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerName.
     * @param value value to set the CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for AddressLine1, using the alias name AddressLine1.
     * @return the AddressLine1
     */
    public String getAddressLine1() {
        return (String)getAttributeInternal(ADDRESSLINE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressLine1.
     * @param value value to set the AddressLine1
     */
    public void setAddressLine1(String value) {
        setAttributeInternal(ADDRESSLINE1, value);
    }

    /**
     * Gets the attribute value for AddressLine2, using the alias name AddressLine2.
     * @return the AddressLine2
     */
    public String getAddressLine2() {
        return (String)getAttributeInternal(ADDRESSLINE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AddressLine2.
     * @param value value to set the AddressLine2
     */
    public void setAddressLine2(String value) {
        setAttributeInternal(ADDRESSLINE2, value);
    }

    /**
     * Gets the attribute value for City, using the alias name City.
     * @return the City
     */
    public String getCity() {
        return (String)getAttributeInternal(CITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for City.
     * @param value value to set the City
     */
    public void setCity(String value) {
        setAttributeInternal(CITY, value);
    }

    /**
     * Gets the attribute value for Country, using the alias name Country.
     * @return the Country
     */
    public String getCountry() {
        return (String)getAttributeInternal(COUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Country.
     * @param value value to set the Country
     */
    public void setCountry(String value) {
        setAttributeInternal(COUNTRY, value);
    }

    /**
     * Gets the attribute value for ZipCode, using the alias name ZipCode.
     * @return the ZipCode
     */
    public Number getZipCode() {
        return (Number)getAttributeInternal(ZIPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ZipCode.
     * @param value value to set the ZipCode
     */
    public void setZipCode(Number value) {
        setAttributeInternal(ZIPCODE, value);
    }

    /**
     * Gets the attribute value for PhoneNo, using the alias name PhoneNo.
     * @return the PhoneNo
     */
    public String getPhoneNo() {
        return (String)getAttributeInternal(PHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhoneNo.
     * @param value value to set the PhoneNo
     */
    public void setPhoneNo(String value) {
        setAttributeInternal(PHONENO, value);
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the MobileNo
     */
    public String getMobileNo() {
        return (String)getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for EmailAddress, using the alias name EmailAddress.
     * @return the EmailAddress
     */
    public String getEmailAddress() {
        return (String)getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmailAddress.
     * @param value value to set the EmailAddress
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for ReceivablesAccount, using the alias name ReceivablesAccount.
     * @return the ReceivablesAccount
     */
    public Number getReceivablesAccount() {
        return (Number)getAttributeInternal(RECEIVABLESACCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceivablesAccount.
     * @param value value to set the ReceivablesAccount
     */
    public void setReceivablesAccount(Number value) {
        setAttributeInternal(RECEIVABLESACCOUNT, value);
    }

    /**
     * Gets the attribute value for NtnNo, using the alias name NtnNo.
     * @return the NtnNo
     */
    public String getNtnNo() {
        return (String)getAttributeInternal(NTNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NtnNo.
     * @param value value to set the NtnNo
     */
    public void setNtnNo(String value) {
        setAttributeInternal(NTNNO, value);
    }

    /**
     * Gets the attribute value for CnicNo, using the alias name CnicNo.
     * @return the CnicNo
     */
    public String getCnicNo() {
        return (String)getAttributeInternal(CNICNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CnicNo.
     * @param value value to set the CnicNo
     */
    public void setCnicNo(String value) {
        setAttributeInternal(CNICNO, value);
    }

    /**
     * Gets the attribute value for FederalTaxPayerId, using the alias name FederalTaxPayerId.
     * @return the FederalTaxPayerId
     */
    public Number getFederalTaxPayerId() {
        return (Number)getAttributeInternal(FEDERALTAXPAYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for FederalTaxPayerId.
     * @param value value to set the FederalTaxPayerId
     */
    public void setFederalTaxPayerId(Number value) {
        setAttributeInternal(FEDERALTAXPAYERID, value);
    }

    /**
     * Gets the attribute value for ProvincialTaxPayerId, using the alias name ProvincialTaxPayerId.
     * @return the ProvincialTaxPayerId
     */
    public Number getProvincialTaxPayerId() {
        return (Number)getAttributeInternal(PROVINCIALTAXPAYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProvincialTaxPayerId.
     * @param value value to set the ProvincialTaxPayerId
     */
    public void setProvincialTaxPayerId(Number value) {
        setAttributeInternal(PROVINCIALTAXPAYERID, value);
    }

    /**
     * Gets the attribute value for SalesPersonId, using the alias name SalesPersonId.
     * @return the SalesPersonId
     */
    public Number getSalesPersonId() {
        return (Number)getAttributeInternal(SALESPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesPersonId.
     * @param value value to set the SalesPersonId
     */
    public void setSalesPersonId(Number value) {
        setAttributeInternal(SALESPERSONID, value);
    }

    /**
     * Gets the attribute value for CustomerNo, using the alias name CustomerNo.
     * @return the CustomerNo
     */
    public DBSequence getCustomerNo() {
        return (DBSequence)getAttributeInternal(CUSTOMERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerNo.
     * @param value value to set the CustomerNo
     */
    public void setCustomerNo(DBSequence value) {
        setAttributeInternal(CUSTOMERNO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param customerId key constituent
     * @param customerNo key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence customerId,
                                       DBSequence customerNo) {
        return new Key(new Object[]{customerId, customerNo});
    }


}
